server:
    port: 80
    
logging:
    file: /exframework-logs/${spring.application.name}/root.log
    level:
        root: INFO
spring:
    main:
        allow-circular-references: true
    application:
        name: "@artifactId@"
    profiles:
        active: "@profile.active@"
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    mvc:
        date-format: yyyy-MM-dd HH:mm:ss.SSS
        pathmatch:
            matching-strategy: ant-path-matcher

canal:
    enable: true
    client:
        instances:
            example:
                cluster-enabled: false
                host: 127.0.0.1
                port: 11111
                batch-size: 1000
                retry-count: 20
                acquire-interval: 1000