server:
    port: 80
    
logging:
    file: /exframework-logs/${spring.application.name}/root.log
    level:
        root: INFO
spring:
    application:
        name: "@artifactId@"
    profiles:
        active: "@profile.active@"
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8

        
feign: 
  sentinel: 
    enabled: true