spring:  
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid:
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 100
        max-open-prepared-statements: 20
        validation-query: select 1 FROM DUAL
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        filters: stat,slf4j
      datasource:   
        master:
          url: jdbc:mysql://127.0.0.1:3306/exframe 
          username: root
          password: localmysql
          druid:
            initial-size: 2
            max-active: 50
            min-idle: 0
            max-wait: 60000
